Repository upbound/platform-ref-aws, pull requests merged in 2022-11, with the labels that each got.

#87 Fix security group selector for rds instance
  package/database/postgres/composition.yaml
Labels: size/XS

#89 Add application abstraction
  README.md
  examples/ghost-claim.yaml
  package/app/composition.yaml
  package/app/definition.yaml
  package/database/sqlinstance/composition.yaml
  package/database/sqlinstance/definition.yaml
Labels: size/L

#83 Bump kube-prometheus-stack chart to latest
  package/cluster/services/composition.yaml
Labels: size/S
